const fs = require("fs");
const path = require("path");

var module = JSON.parse(fs.readFileSync(path.join(__dirname, "module.json"), "utf-8"));

exports.module = module["module"];
exports.bootFile = module["bootFile"];

exports.infoText = {
    "core-extensions": "Cocos2d Core extensions",
    "core": 'Engine core modules, includes Director, Node, Scene, Layer, Sprite, LabelTTF, EventManger, Scheduler and Texture2D. The default render is canvas',
    "webgl": "Cocos2d WebGL support",
    "debugger": 'Log system and debug informations',
    "kazmath": 'Math lib for webgl',
    "shaders": 'Shaders',
    "render-texture": 'RenderTexture node for custom rendering',
    "labels": 'Label nodes including LabelBMFont, LabelAtlas',
    "motion-streak": 'MotionStreak which can manage a ribbon based on its motion',
    "node-grid": 'Base node of effects',
    "shape-nodes": 'DrawNode can be used to render lines, polygons, curves, etc',
    "clipping-nodes": 'ClippingNode can clip hosted nodes with shape or texture as stencil',
    "effects": 'Some effects',
    "actions": 'Configurable actions for animating nodes with position, scale, etc',
    "actions3d": 'Effects that can be applied to nodes, like page turn, shake, wave, etc',
    "progress-timer": 'ProgressTimer node which can transform a node into a progression bar',
    "transitions": 'Scene transition effects',
    "compression": 'Compression of tilemap and particle',
    "particle": 'ParticleSystem node and built in particle effects',
    "text-input": 'Nodes for simple text inputing',
    "menus": 'Menu and MenuItem nodes for creating game menu',
    "tilemap": 'TMX file parser for creating tile map layers',
    "parallax": 'Parallax effect which can be applied to layers',
    "audio": 'Audio system',
    "gui": 'Another GUI extension with a set of useful widgets',
    "ccbreader": 'CocosBuilder editor support',
    "editbox": 'Edit Box for more complex text inputing',
    "ccui": 'Cocos UI widgets with layout support',
    "cocostudio": 'CocoStudio editor support',
    "pluginx": 'Social network API plugins',
    "physics": 'Physics node for Box2d and Chipmunk',
    "socketio": 'ScoketIO library support',
    "gaf": 'Gaf library support',
    "box2d": 'Built in box2d physics engine support',
    "chipmunk": 'Built in Chipmunk physics engine support',
    "spine": "The spine support library",
    "ccpool": "Sprite recycling pool",
    "sprite-batch-node": "A type of sprite that can host sprites using the same texture and enable texture batching to improve performance",

    //WebGL扩展（页面中判断勾选了WebGL后，根据已选模块自动选中下列包）
    "core-webgl": "",
    "clipping-nodes-webgl": "",
    "core-extensions-webgl": "",
    "sprite-batch-node-webgl": "",
    "labels-webgl": "",
    "particle-webgl": "",
    "physics-webgl": "",
    "progress-timer-webgl": "",
    "render-texture-webgl": "",
    "shape-nodes-webgl": "",
    "tilemap-webgl": "",
    "cocostudio-webgl": "",
    "spine-webgl": "",
    "gui-webgl": "",
    "gaf-webgl": ""
};

//排序列表
exports.sortList = [
    "core",
    "core-webgl",
    "webgl",
    "core-extensions",
    "core-extensions-webgl",
    "debugger",
    "actions",
    "audio",
    "menus",
    "kazmath",
    "shaders",
    "render-texture",
    "render-texture-webgl",
    "sprite-batch-node",
    "sprite-batch-node-webgl",
    "labels",
    "labels-webgl",
    "motion-streak",
    "node-grid",
    "shape-nodes",
    "shape-nodes-webgl",
    "clipping-nodes",
    "clipping-nodes-webgl",
    "effects",
    "actions3d",
    "progress-timer",
    "progress-timer-webgl",
    "transitions",
    "compression",
    "particle",
    "particle-webgl",
    "text-input",
    "tilemap",
    "tilemap-webgl",
    "parallax",
    "gui",
    "gui-webgl",
    "ccbreader",
    "editbox",
    "ccui",
    "cocostudio",
    "cocostudio-webgl",
    "ccpool",
    "pluginx",
    "physics",
    "physics-webgl",
    "socketio",
    "gaf",
    "box2d",
    "chipmunk",
    "spine",
    "spine-webgl",
    "gaf-webgl"
];

//页面上默认隐藏的列表1为隐藏，0或者不存在为不隐藏
exports.hiddenList = {
    'core-extensions': 1,
    'kazmath': 1,
    'shaders': 1,
    'node-grid': 1,
    'compression': 1,
    'effects': 1,
    'physics': 1,

    "core-webgl": 1,
    "clipping-node-webgl": 1,
    "core-extensions-webgl": 1,
    "sprite-batch-node-webgl": 1,
    "labels-webgl": 1,
    "particle-webgl": 1,
    "physics-webgl": 1,
    "progress-timer-webgl": 1,
    "render-texture-webgl": 1,
    "shape-nodes-webgl": 1,
    "tilemap-webgl": 1,
    "cocostudio-webgl": 1,
    "spine-webgl": 1,
    "clipping-nodes-webgl": 1,
    "gui-webgl": 1,
    "gaf-webgl": 1
};

//express版本默认选中的包
exports.express = {
    "core": 1,
    "debugger": 1,
    "actions": 1,
    "audio": 1,
    "menus": 1
};